ip:
  this:
    ip: "192.168.199.253"
    port: 12349

  robot:
    ip: "192.168.199.100"
    port: 12349

JOY_send:
  manipulator_joy:
    data_num: 0
    dst_name: "robot"
    topic_name: "/joy_manipulator"