ip:
  this:
    ip: "192.168.199.253"
    port: 12340

  robot:
    ip: "192.168.199.100"
    port: 12340

image_rcv:
  image1:
    data_num: 101
    topic_name: "/cam_image/front"

  image2:
    data_num: 100
    topic_name: "/cam_image/left"
  
  image3:
    data_num: 99
    topic_name: "/cam_image/right"
