ip:
  this:
    ip: "192.168.199.253"
    port: 12346

  robot:
    ip: "192.168.199.100"
    port: 12346

image_rcv:
  split_image1:
    data_num: 101
    topic_name: "/split_image/output/vertical00/horizontal01"

  split_image2:
    data_num: 100
    topic_name: "/split_image/output/vertical00/horizontal00"
  
  360_merge:
    data_num: 99
    topic_name: "/dual_fisheye_to_panorama/output"
