ip:
  this:
    ip: "192.168.199.253"
    port: 12345

  robot:
    ip: "192.168.199.100"
    port: 12345

STMTX_send:
  STM_tx_data:
    data_num: 0
    dst_name: "robot"
    topic_name: "/STM_tx_data"

STMRX_rcv:
  STM_rx_data:
    data_num: 1
    topic_name: "/STM_rx_data"

BOOLEAN_send:
  comm_stat_oper:
    data_num: 3
    dst_name: "robot"
    topic_name: "/comm_stat/operator"

BOOLEAN_rcv:
  comm_stat_robot:
    data_num: 5
    topic_name: "/comm_stat/robot"

STRING_send:
  operator_request:
    data_num: 6
    dst_name: "robot"
    topic_name: "/udp_request/operator"
  
STRING_rcv:
  robot_request:
    data_num: 7
    topic_name: "/udp_request/robot"
