ip:
  this:
    ip: "192.168.199.253"
    port: 12884

  robot:
    ip: "192.168.199.100"
    port: 12884

JOY_send:
  manipulator_joy:
    data_num: 0
    dst_name: "robot"
    topic_name: "/joy_manipulator"

FLOAT_ARR_rcv:
  manipulator_angle:
    data_num: 1
    topic_name: "/mani_angle"

INT_send:
  manipulator_mission_start:
    data_num: 2
    topic_name: "/dex_mode"
    dst_name: "robot"

INT_rcv:
  manipulator_mission_end:
    data_num: 3
    topic_name: "/dex_joy_mode"

STRING_send:
  victim_box_start:
    data_num: 4
    topic_name: "/victim_start"
    dst_name: "robot"

STRING_rcv: 
  victim_box_end:
    data_num: 5
    topic_name: "/victim_end"