ip:
  this:
    ip: "192.168.199.253"
    port: 12340

  robot:
    ip: "192.168.199.100"
    port: 12340

image_rcv:
  image1:
    data_num: 101
    topic_name: "/front/usb_cam/image_raw"

  image2:
    data_num: 100
    topic_name: "/left/usb_cam/image_raw"
  
  image3:
    data_num: 99
    topic_name: "/right/usb_cam/image_raw"
