ip:
  this:
    ip: "192.168.199.100"
    port: 12884

  operator:
    ip: "192.168.199.253"
    port: 12884

JOY_rcv:
  manipulator_joy:
    data_num: 0
    topic_name: "/joy_manipulator"

FLOAT_ARR_send:
  manipulator_angle:
    data_num: 1
    topic_name: "/mani_angle"
    dst_name: "operator"

INT_rcv:
  manipulator_mission_start:
    data_num: 2
    topic_name: "/dex_mode"

INT_send:
  manipulator_mission_end:
    data_num: 3
    topic_name: "/dex_joy_mode"
    dst_name: "operator"

STRING_rcv:
  victim_box_start:
    data_num: 4
    topic_name: "/victim_start"

STRING_send:
  victim_box_end:
    data_num: 5
    topic_name: "/victim_end"
    dst_name: "operator"