ip:
  this:
    ip: "192.168.199.100"
    port: 12346

  operator:
    ip: "192.168.199.253"
    port: 12346

image_send:
  split_image1:
    data_num: 101
    topic_name: "/split_image/output/vertical00/horizontal01"
    height: 240
    width: 480
    quality: 80
    dst_name: "operator"

  split_image2:
    data_num: 100
    topic_name: "/split_image/output/vertical00/horizontal00"
    height: 240
    width: 480
    quality: 80
    dst_name: "operator"
  
  360_merge:
    data_num: 99
    topic_name: "/dual_fisheye_to_panorama/output/compressed"
    height: 300
    width: 600
    quality: 80
    dst_name: "operator"

