ip:
  this:
    ip: "192.168.199.253"
    port: 12345

  robot:
    ip: "192.168.199.100"
    port: 12345

STMTX_send:
  STM_tx_data:
    data_num: 0
    dst_name: "robot"
    topic_name: "/STM_tx_data"

STMRX_rcv:
  STM_rx_data:
    data_num: 0
    topic_name: "/STM_rx_data"
