ip:
  this:
    ip: "192.168.199.253"
    port: 12346

  robot:
    ip: "192.168.199.100"
    port: 12346

image_rcv:
  main_cam:
    data_num: 100
    topic_name: "/usb_cam/c920"
  
  360_merge:
    data_num: 99
    topic_name: "/insta360_image"
