ip:
  this:
    ip: "192.168.199.100"
    port: 12345

  operator:
    ip: "192.168.199.253"
    port: 12345

STMTX_rcv:
  STM_tx_data:
    data_num: 0
    topic_name: "STM_tx_data"

STMRX_send:
  STM_rx_data:
    data_num: 0
    topic_name: "STM_rx_data"
    dst_name: "operator"
